### PR TITLE
Add kafka status to health check

### PR DESCRIPTION
**Pull request by kevinwlau**

### CODE REVIEW

**Comment by kevinwlau** [comment]
Found an issue where the logging output rate keeps growing until the application runs out of resources.

image

**Comment by yeekangc** [comment]
@kevinwlau, do we really need the beans.xml?

**Comment by kevinwlau** [comment]
> @kevinwlau, do we really need the beans.xml?

Yes, I tested without the beans.xml and CDI doesn't work properly. End up with a NullPointer when trying to access the injected `Consumer`

**Comment by yeekangc** [comment]
Should look into that further but will take the changes.

**Pull request merged**
